name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Extract project details
      id: project-details
      run: |
        ARTIFACT_ID=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "::set-output name=artifact_id::$ARTIFACT_ID"
        echo "::set-output name=version::$VERSION"

    - name: List contents of target directory
      run: ls -la target
        
    - name: Run tests with Maven
      run: mvn test
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/\${{ steps.project-details.outputs.artifact_id }}:\${{ steps.project-details.outputs.version }}

    - name: Update Docker Hub description
      run: |
        curl -X PATCH \
        -H "Content-Type: application/json" \
        -u "${{ secrets.DOCKER_HUB_USERNAME }}:${{ secrets.DOCKER_HUB_PASSWORD }}" \
        -d '{"description": "This is the Docker image for the project ${{ steps.project-details.outputs.artifact_id }} version ${{ steps.project-details.outputs.version }}."}' \
        https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_HUB_USERNAME }}/\${{ steps.project-details.outputs.artifact_id }}/
      
